from langchain_core.language_models import BaseChatModel
from langchain_core.messages import BaseMessage
from langchain_google_genai import ChatGoogleGenerativeAI
from langchain_ibm import ChatWatsonx

from abc import ABC, abstractmethod

from src.utils import LOG, ERR_GEMINI_API_KEY_MISSING, ERR_WATSONX_API_KEY_MISSING

class LLMBaseWrapper(ABC):
    """
    Abstract base class for wrapping different LLM providers 
    (e.g., Gemini, Watsonx).

    This class provides a common interface for creating the LLM instance, retrieving its name, and extracting token usage 
    from raw responses.
    
    Attributes:
        config (Any): The application configuration object containing LLM settings.
        llm_instance (BaseChatModel or None): The instantiated LangChain chat model object.
    """
    def __init__(self, config):
        self.config = config
        self.llm_instance: BaseChatModel = None

    @abstractmethod
    def _create_llm_instance(self, config):
        """
        Creates and returns the concrete LangChain chat model instance (e.g., ChatGoogleGenerativeAI or ChatWatsonx).

        Args:
            config (Any): The application configuration object.

        Returns:
            BaseChatModel: The instantiated chat model.

        Raises:
            RuntimeError: If necessary API keys or credentials are missing.
        """
        pass

    @abstractmethod
    def get_output_tokens(self, raw_response: BaseMessage) -> int:
        """
        Extracts the number of output tokens generated by the LLM from the raw response object.

        Args:
            raw_response: The raw response object returned by the LangChain LLM invocation.

        Returns:
            int: The count of output tokens, or 0 if not found.
        """
        pass
        
    @abstractmethod
    def get_provider_name(self) -> str:
        """
        Returns the canonical name of the LLM provider.

        Returns:
            str: The provider name (e.g., "gemini", "watsonx").
        """
        
        pass
        
    def get_llm_instance(self) -> BaseChatModel:
        if not self.llm_instance:
            self.llm_instance = self._create_llm_instance(self.config)
        
        return self.llm_instance
    

class GeminiWrapper(LLMBaseWrapper):
    """
    Wrapper for the Google Gemini LLM provider, inheriting from LLMBaseWrapper.
    """
    
    def get_provider_name(self) -> str:
        return "gemini"
        
    def _create_llm_instance(self, config):
        if config.gemini.api_key:
            
            LOG.info(f"Creating Gemini LLM ...")
            
            return ChatGoogleGenerativeAI(
                model = config.gemini.model,
                temperature = config.gemini.temperature,
                max_output_tokens = config.gemini.max_output_tokens,
                google_api_key = config.gemini.api_key,
            )
            
        else:
            raise RuntimeError(ERR_GEMINI_API_KEY_MISSING)

    def get_output_tokens(self, raw_response: BaseMessage) -> int:
        return raw_response.usage_metadata.get("output_tokens", 0)


class WatsonxWrapper(LLMBaseWrapper):
    """
    Wrapper for the IBM Watsonx LLM provider, inheriting from LLMBaseWrapper.
    """
    
    def get_provider_name(self) -> str:
        return "watsonx"
        
    def _create_llm_instance(self, config):
        
        if config.watsonx.api_key:
            
            LOG.info(f"Creating Watsonx LLM: model ...")

            generation_params = {
                # 1. QUANTITY: Reads 4096 from your YAML.
                # If this value is too low, the JSON will be truncated.
                "max_new_tokens": config.watsonx.max_tokens,

                # 2. DETERMINISM: Force "greedy" to avoid JSON syntax errors.
                # (Ignore temperatures > 0 if present, to protect data integrity)
                "decoding_method": "greedy",
                "temperature": config.watsonx.temperature,

                # 3. CLEANUP: Stop the model as soon as it closes the JSON array
                # or if it tries to open a markdown block.
                "stop_sequences": ["]\n", "```"],

                # 4. ANTI-LOOP: Light penalty to avoid infinite repetitions
                "repetition_penalty": 1.05,

                "min_new_tokens": 1
            }
            
            return ChatWatsonx(
                model_id  = config.watsonx.model,
                api_key = config.watsonx.api_key,
                url = config.watsonx.endpoint, 
                project_id = config.watsonx.project_id,
                params = generation_params
            )
            
        else:
            raise RuntimeError(ERR_WATSONX_API_KEY_MISSING)

    def get_output_tokens(self, raw_response: BaseMessage) -> int:
        return raw_response.usage_metadata.get("output_tokens", 0) 
       