from __future__ import annotations

import json
import re
from typing import Any, Dict, List, Optional, Set, Tuple

from langchain_core.messages import BaseMessage, HumanMessage, SystemMessage

from src.config import AppConfig
from src.llm import get_llm_wrapper
from src.llm.llm_wrappers import LLMBaseWrapper
from src.llm.galois_prompts import (
    build_table_scan_first_prompt,
    build_table_scan_iter_prompt,
)
from src.galois_wo.schema_manager_wo import GaloisWOSchemaManager
from src.utils import sql_query_parser
from src.utils.invoke_with_backoff import invoke_with_backoff
from src.utils.logging_config import LOG
from src.utils import ERR_LLM_PARSING_FAILURE


class GaloisExecutor:
    """
    Core execution engine for the Galois-WO pipeline (Table-Scan).

    Responsibilities:
      - Parse the SQL query.
      - Retrieve schema information for the target table.
      - Build the first and iterative prompts (Algorithm 1 in the paper).
      - Interact with the LLM to collect tuples.
      - Deduplicate tuples across iterations.
    """

    def __init__(self, config: AppConfig, dataset: str, max_iter: int = 4) -> None:
        """
        Parameters
        ----------
        config : AppConfig
            Global application configuration (loaded from config.yaml).
        dataset : str
            Dataset name (e.g. WORLD, GEO, MOVIES, PRESIDENTS, ...).
        max_iter : int, optional
            Maximum number of Table-Scan iterations, used as a default if
            not overridden at call-time.
        """
        self.config = config
        self.dataset = dataset.upper()
        self.max_iter = max_iter

        # LLM wrapper and underlying chat model (Watsonx, Gemini, etc.)
        self.llm_wrapper: LLMBaseWrapper = get_llm_wrapper(config)
        self.llm = self.llm_wrapper.get_llm_instance()

        # Schema manager for Galois-WO, connecting directly to the DuckDB file
        self.schema_mgr = GaloisWOSchemaManager(self.dataset)

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------
    def table_scan(
        self,
        sql_query: str,
        conditions_to_push: Optional[List[str]] = None,
        max_iter: Optional[int] = None,
    ) -> List[Dict[str, Any]]:
        """
        Execute the Table-Scan operator for a single-table SQL query.

        The logic follows Algorithm 1 (Table-Scan) from the GALOIS paper:

          1. Build the first prompt (genFirstPrompt) using the table schema
             and the conditions to push down.
          2. Query the LLM and parse the returned tuples.
          3. Iteratively:
             - build an iterative prompt (genIterativePrompt),
             - query the LLM again,
             - parse additional tuples,
             - stop when no new tuples are produced or the max number of
               iterations is reached.

        Parameters
        ----------
        sql_query : str
            Original SQL query.
        conditions_to_push : list of str, optional
            Subset of WHERE conditions chosen by the logical optimizer
            (Galois). If provided, ONLY these conditions are used inside
            the LLM prompt. If None, the full original WHERE clause is used.
        max_iter : int, optional
            Maximum number of iterations for this call. If None, the
            default self.max_iter is used.

        Returns
        -------
        List[Dict[str, Any]]
            List of unique tuples generated by the LLM, each represented
            as a dictionary {column_name: value}.
        """
        if max_iter is None:
            max_iter = self.max_iter

        LOG.info(
            f"[GaloisExecutor] Starting Table-Scan for dataset={self.dataset}, "
            f"max_iter={max_iter}"
        )

        # 1) Parse the SQL query into a structured representation
        parsed = sql_query_parser.parse_sql(sql_query)
        table_name = parsed["from_table"]
        original_where = parsed.get("where_conditions") or []

        # Decide which conditions to actually push down
        if conditions_to_push:
            where_conditions = conditions_to_push
            LOG.info(
                "[GaloisExecutor] Using pushed-down conditions from plan: %s",
                where_conditions,
            )
        else:
            where_conditions = original_where
            LOG.info(
                "[GaloisExecutor] Using original WHERE conditions: %s",
                where_conditions,
            )

        where_clause = " AND ".join(where_conditions) if where_conditions else None

        # 2) Resolve the exact table name and retrieve table attributes
        exact_table = self.schema_mgr.get_exact_table_name(table_name) or table_name
        attributes = self.schema_mgr.get_attributes(exact_table)

        if not attributes:
            raise ValueError(f"No attributes found for table '{exact_table}'")

        # If no PK is defined, the schema manager may return an empty list.
        # Here we only need attributes, so it's fine.
        json_example = self.schema_mgr.get_json_schema_example(exact_table, attributes)

        LOG.debug(
            "[GaloisExecutor] Parsed query -> table=%s, where=%s, attrs=%s",
            exact_table,
            where_clause,
            attributes,
        )

        # 3) Build initial conversation: System + first human prompt
        system_msg = SystemMessage(
            content=(
                "You are a data extraction engine. "
                "Your task is to output ONLY valid JSON objects that represent "
                "rows of a SQL table. Never include explanations or markdown."
            )
        )

        first_prompt = build_table_scan_first_prompt(
            table_name=exact_table,
            attributes=attributes,
            where_clause=where_clause,
            json_example=json_example,
        )
        history: List[BaseMessage] = [system_msg, HumanMessage(content=first_prompt)]

        # 4) Iteratively query the LLM and collect tuples
        all_rows: List[Dict[str, Any]] = []
        seen_rows: Set[Tuple[Tuple[str, Any], ...]] = set()

        for i in range(max_iter):
            LOG.info("[GaloisExecutor] Table-Scan iteration %d/%d", i + 1, max_iter)

            # Call the LLM with exponential backoff
            raw_response = invoke_with_backoff(
                self.llm,
                history,
                max_retries=self.config.galois_execution.max_retries,
                base_delay=self.config.galois_execution.backoff_sec,
                )


            # Parse tuples produced in this iteration
            iter_rows = self._parse_table_scan_response(raw_response, exact_table)
            has_new = self._merge_new_rows(iter_rows, all_rows, seen_rows)

            # Append AI message to history (H ← H ∪ {ai})
            if isinstance(raw_response, BaseMessage):
                history.append(raw_response)

            if not has_new:
                LOG.info(
                    "[GaloisExecutor] No new tuples returned by LLM. "
                    "Stopping Table-Scan."
                )
                break

            # Prepare next iteration prompt
            iter_prompt = build_table_scan_iter_prompt()
            history.append(HumanMessage(content=iter_prompt))

        LOG.info(
            "[GaloisExecutor] Table-Scan completed. "
            "total_rows=%d unique tuples collected.",
            len(all_rows),
        )

        return all_rows

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------
    def _parse_table_scan_response(
        self,
        raw_response: Any,
        table_name: str,
    ) -> List[Dict[str, Any]]:
        """
        Convert the raw LLM response into a list of dicts representing rows.

        This function is defensive and tries multiple strategies to extract
        and parse JSON from the model output. It supports:

          - Responses as BaseMessage or plain strings.
          - Responses as lists of chunks (e.g. [{"text": "..."}, ...]).
          - Extra whitespace, newlines, or markdown fences (```json ... ```).
          - JSON wrapped in additional prose.
          - Recovery of the *first* complete row object even if the full JSON
            is truncated or invalid (common with long outputs).
        """
        # 1) Extract content from the LLM response
        if isinstance(raw_response, BaseMessage):
            content = raw_response.content
        else:
            content = str(raw_response)

        # Some providers may return a list of chunks instead of a single string
        if isinstance(content, list):
            chunks: List[str] = []
            for c in content:
                if isinstance(c, dict) and "text" in c:
                    chunks.append(str(c["text"]))
                else:
                    chunks.append(str(c))
            text = " ".join(chunks)
        else:
            text = str(content)

        text = text.strip()

        # 2) Remove possible markdown fences ```...``` and labels like ```json
        if text.startswith("```"):
            # Strip outer backticks and remove the first line if it is a 'json' label
            text = text.strip("`")
            if "\n" in text:
                first_line, rest = text.split("\n", 1)
                if first_line.strip().lower().startswith("json"):
                    text = rest
                else:
                    text = rest

        def try_load_json(candidate: str) -> Optional[Any]:
            try:
                return json.loads(candidate)
            except Exception:
                return None

        # 3) First attempt: parse the whole content as JSON
        obj = try_load_json(text)

        # 4) If that fails, search for any block that looks like JSON:
        #    a {...} object or a [...] array
        if obj is None:
            matches = re.findall(r"(\{[\s\S]*\}|\[[\s\S]*\])", text)
            for candidate in matches:
                candidate = candidate.strip()
                parsed = try_load_json(candidate)
                if parsed is not None:
                    obj = parsed
                    break

        # 5) If still None, try to recover the FIRST row object from the array
        #    associated with the given table, e.g.:
        #
        #       {"movie": [ { ... }, { ... (truncated) } ... ]}
        #
        if obj is None:
            key = f'"{table_name}"'
            start_key = text.find(key)
            if start_key != -1:
                # Find the '[' that starts the array after "<table_name>"
                idx_bracket = text.find("[", start_key)
                if idx_bracket != -1:
                    # Find the first '{' that starts the first row object
                    idx_obj_start = text.find("{", idx_bracket)
                    if idx_obj_start != -1:
                        depth = 0
                        in_string = False
                        escape = False
                        end_index = None

                        for i in range(idx_obj_start, len(text)):
                            ch = text[i]

                            if escape:
                                escape = False
                                continue

                            if ch == "\\":
                                escape = True
                                continue

                            if ch == '"':
                                in_string = not in_string
                                continue

                            if not in_string:
                                if ch == "{":
                                    depth += 1
                                elif ch == "}":
                                    depth -= 1
                                    if depth == 0:
                                        end_index = i
                                        break

                        if end_index is not None:
                            candidate = text[idx_obj_start : end_index + 1]
                            parsed = try_load_json(candidate)
                            if parsed is not None:
                                LOG.warning(
                                    "[GaloisExecutor] Recovered first row object "
                                    "from partially invalid/truncated output."
                                )
                                # Return a single-row list here
                                return [parsed]

        # 6) If still None, log and return no rows
        if obj is None:
            LOG.error(
                ERR_LLM_PARSING_FAILURE.format(
                    f"Table-Scan output for table {table_name}: {text[:400]}"
                )
            )
            return []

        rows: List[Dict[str, Any]] = []

        # 7) Extract rows depending on the structure:
        #   { "<table_name>": [ {row}, ... ] }
        #   { "result_set": [ {row}, ... ] }
        #   [ {row}, ... ]
        #   { ... } (single row)
        if isinstance(obj, dict):
            if table_name in obj and isinstance(obj[table_name], list):
                for item in obj[table_name]:
                    if isinstance(item, dict):
                        rows.append(item)
            elif "result_set" in obj and isinstance(obj["result_set"], list):
                for item in obj["result_set"]:
                    if isinstance(item, dict):
                        rows.append(item)
            else:
                rows.append(obj)
        elif isinstance(obj, list):
            for item in obj:
                if isinstance(item, dict):
                    rows.append(item)

        LOG.debug(
            "[GaloisExecutor] Parsed %d rows from LLM response for table=%s",
            len(rows),
            table_name,
        )
        return rows

    def _merge_new_rows(
        self,
        new_rows: List[Dict[str, Any]],
        all_rows: List[Dict[str, Any]],
        seen_rows: Set[Tuple[Tuple[str, Any], ...]],
    ) -> bool:
        """
        Merge `new_rows` into `all_rows`, updating `seen_rows` to avoid duplicates.

        Parameters
        ----------
        new_rows : list of dict
            Tuples returned in the current iteration.
        all_rows : list of dict
            Global list of all tuples collected so far.
        seen_rows : set
            Set of hashable keys representing already seen tuples.

        Returns
        -------
        bool
            True if at least one new row was added, False otherwise.
        """
        added_any = False

        for row in new_rows:
            key = self._normalise_row(row)
            if key in seen_rows:
                continue
            seen_rows.add(key)
            all_rows.append(row)
            added_any = True

        return added_any

    @staticmethod
    def _normalise_row(row: Dict[str, Any]) -> Tuple[Tuple[str, Any], ...]:
        """
        Convert a row-dict into a hashable, order-independent key.

        This is used to store rows in a set (seen_rows) and detect
        duplicates regardless of column ordering.
        """
        return tuple(sorted(row.items()))
