llm_provider: "watsonx"

database:
  run:  GEO, Movies

galois_execution:
  max_retries: 3
  backoff_sec: 1.5
  scan: "auto"
  confidence_threshold: 0.6
  max_iter: 3

io:
  queries_dir: "../data"
  prompts_dir: "./prompts"
  outputs_dir: "data/.outputs"

logging:
  level: "INFO"
  json_format: true

gemini:
  model: "gemini-2.5-flash"
  temperature: 0
  max_output_tokens: 2000

watsonx:
  model: "meta-llama/llama-3-3-70b-instruct"
  temperature: 0
  max_tokens: 4096

open_router:
  model: "openai/gpt-4o-mini"
  temperature: 0
  max_tokens: 4096


rag:
  top_k: 50