model:
  provider: Google Gemini
  name: gemini-2.5-flash
  temperature: 0.0

confidence:
  tau: 0.7
  key_fn: "LLM keys" #insert the API keys for LLM

execution:
  max_retries: 3
  backoff_sec: 1.5
  scan: "auto"

io:
  queries_dir: "../data"
  prompts_dir: "./prompts"
  outputs_dir: "../../verification-test-tool/tests"

logging:
  level: "INFO"
  json: true

gemini:
  model: "gemini-2.5-flash"
  temperature: 0.7
  max_output_tokens: 2000

#grok:
  #model: "grok-3"
  #max_tokens: 100


