database:
  run:  GEO, Movies

execution:
  max_retries: 3
  backoff_sec: 1.5
  scan: "auto"

io:
  queries_dir: "../data"
  prompts_dir: "./prompts"
  outputs_dir: "data/.outputs"

logging:
  level: "INFO"
  json_format: true

gemini:
  model: "gemini-2.5-flash"
  temperature: 0.7
  max_output_tokens: 2000

grok:
  model: "grok-3"
  max_tokens: 100


