database:
  run:  GEO, Movies

llm:
  provider: "watsonx"
  model: "ibm/granite-3-8b-instruct"
  temperature: 0.1


execution:
  max_retries: 3
  backoff_sec: 1.5
  scan: "auto"

io:
  queries_dir: "../data"
  prompts_dir: "./prompts"
  outputs_dir: "data/.outputs"

logging:
  level: "INFO"
  json_format: true


